import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Building2, Loader2, AlertCircle, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useUserStore } from '@/stores/authStore';
import { useAuth } from '@/hooks/useAuth';
import { useGetOrgDetailsBySlug, useUpdateOrganization, useGetOrganizationList } from '@/hooks/useJobsApi';
import { CreateOrg } from '@/components/organisation/CreateOrg';
import UnifiedAuthDialog from '@/components/auth/UnifiedAuthDialog';
import { toast } from 'sonner';
import type { OrganizationProfile } from '@/stores/authStore';

export const Route = createFileRoute('/join/$associationSlug')({
  component: JoinOrgRoute,
});

function JoinOrgRoute() {
  // Route.useParams() will be typed correctly once routeTree.gen.ts is regenerated by the dev server
  const { associationSlug } = Route.useParams() as { associationSlug: string };
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { checkSession } = useAuth();
  const user = useUserStore((state) => state.user);
  const updateOrganizationMutation = useUpdateOrganization();

  const [showAuthDialog, setShowAuthDialog] = useState(false);
  const [showCreateOrg, setShowCreateOrg] = useState(false);
  // 'confirm' = logged-in user with existing org but no MSME association yet
  const [showConfirm, setShowConfirm] = useState(false);
  const [isAttaching, setIsAttaching] = useState(false);

  // Fetch the MSME org details to validate the slug and display its name/logo
  const { data: orgDetails, isLoading: isLoadingOrg, isError: isOrgError } = useGetOrgDetailsBySlug(associationSlug);

  const profile = user?.profile as OrganizationProfile | undefined;
  // Only fetch organization list as a fallback when we don't have an org id in the session profile.
  // This avoids calling the org list API on the public join landing page.
  const shouldFetchOrgListFallback = !!user && !!profile && !profile.id;
  const { data: orgList } = useGetOrganizationList(shouldFetchOrgListFallback);

  // Once the user is logged in, decide what to show
  useEffect(() => {
    if (!user) return;

    if (!user.profile) {
      // Logged in but no org yet — show CreateOrg with the locked slug
      setShowCreateOrg(true);
      return;
    }

    const currentProfile = user.profile as OrganizationProfile;
    const alreadyAssociated = currentProfile.type?.startsWith('associationslug:');

    if (alreadyAssociated) {
      // Already under an MSME — just go to dashboard
      navigate({ to: '/dashboard', replace: true });
    } else {
      // Has an org but not yet associated with any MSME — show confirmation
      setShowConfirm(true);
    }
  }, [user, navigate]);

  const handleAuthSuccess = async () => {
    setShowAuthDialog(false);
    // Refresh session so user state is populated
    await checkSession();
    // The useEffect above will react to the updated user state
  };

  const handleOrgCreated = async () => {
    setShowCreateOrg(false);
    await checkSession();
    queryClient.invalidateQueries();
    toast.success('Organization created!');
    navigate({
      to: '/dashboard',
      search: { associationslug: associationSlug },
      replace: true,
    });
  };

  // Called when an already-registered user confirms they want to attach to the MSME
  const handleAttachExistingOrg = async () => {
    const currentProfile = user?.profile as OrganizationProfile | undefined;
    const orgId = currentProfile?.id || orgList?.[0]?.id;
    const orgSlug = currentProfile?.slug || orgList?.[0]?.slug;
    const orgName = currentProfile?.name || orgList?.[0]?.name;
    const orgLogo = currentProfile?.logo || orgList?.[0]?.logo;

    if (!orgId || !orgName) {
      toast.error('Could not find your organization. Please try again.');
      return;
    }

    console.log('🔗 Attaching org to MSME:', { orgId, slug: orgSlug, associationSlug });

    setIsAttaching(true);
    try {
      // Prefer metadata assembled from the session profile.
      // (We avoid depending on the org list API response shape here.)
      const metadata: Record<string, any> = {
        address: currentProfile?.address || '',
        gstNumber: currentProfile?.gstNumber || '',
        contactPersonName: currentProfile?.contactPersonName || '',
        contactEmail: currentProfile?.contactEmail || '',
        contactPhone: currentProfile?.contactPhone || '',
        website: currentProfile?.website || '',
        description: currentProfile?.description || '',
      };

      await updateOrganizationMutation.mutateAsync({
        organizationId: orgId,
        organizationData: {
          name: orgName,
          logo: orgLogo,
          metadata,
          slug: orgSlug,
          type: `associationslug:${associationSlug}`,
        },
      });

      await checkSession();
      queryClient.invalidateQueries();
      toast.success(`Organization linked to ${orgDetails?.name ?? associationSlug}!`);
      navigate({
        to: '/dashboard',
        search: { associationslug: associationSlug },
        replace: true,
      });
    } catch (error: any) {
      toast.error('Failed to link organization. Please try again.');
      console.error('Attach org error:', error);
    } finally {
      setIsAttaching(false);
    }
  };

  // --- Loading state ---
  if (isLoadingOrg) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center space-y-3">
          <Loader2 className="h-8 w-8 animate-spin text-primary mx-auto" />
          <p className="text-muted-foreground">Loading organization details...</p>
        </div>
      </div>
    );
  }

  // --- Invalid slug ---
  if (isOrgError || !orgDetails) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="max-w-md mx-auto text-center space-y-4 px-4">
          <AlertCircle className="h-12 w-12 text-destructive mx-auto" />
          <h1 className="text-2xl font-bold">Organization not found</h1>
          <p className="text-muted-foreground">
            The invite link you followed is invalid or the organization no longer exists.
          </p>
          <Button variant="outline" onClick={() => navigate({ to: '/' })}>
            Go to home
          </Button>
        </div>
      </div>
    );
  }

  // --- Logged-in user with no profile — show CreateOrg inline ---
  if (user && !user.profile && showCreateOrg) {
    return (
      <div className="min-h-screen bg-background">
        {/* MSME org banner */}
        <div className="border-b bg-muted/40">
          <div className="container mx-auto px-4 py-3 flex items-center gap-3">
            {orgDetails.logo ? (
              <img src={orgDetails.logo} alt={orgDetails.name} className="h-8 w-8 rounded object-cover" />
            ) : (
              <Building2 className="h-6 w-6 text-muted-foreground" />
            )}
            <span className="text-sm text-muted-foreground">
              You are joining <span className="font-semibold text-foreground">{orgDetails.name}</span> as a member organization
            </span>
          </div>
        </div>

        <div className="container mx-auto px-4 py-8 max-w-2xl">
          <CreateOrg
            isOpen={true}
            lockedAssociationSlug={associationSlug}
            onSuccess={handleOrgCreated}
          />
        </div>
      </div>
    );
  }

  // --- Logged-in user with existing org, no MSME association yet — show confirmation ---
  if (user && user.profile && showConfirm) {
    const currentProfile = user.profile as OrganizationProfile;
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="container mx-auto px-4 max-w-lg">
          <Card>
            <CardHeader className="text-center pb-2">
              <div className="flex items-center justify-center mb-3">
                {orgDetails?.logo ? (
                  <img
                    src={orgDetails.logo}
                    alt={orgDetails.name}
                    className="h-16 w-16 rounded-lg object-cover border"
                  />
                ) : (
                  <div className="h-16 w-16 rounded-lg bg-primary/10 flex items-center justify-center">
                    <Building2 className="h-8 w-8 text-primary" />
                  </div>
                )}
              </div>
              <CardTitle className="text-xl">{orgDetails?.name ?? associationSlug}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-center">
                <p className="text-muted-foreground text-sm">
                  You are about to link{' '}
                  <span className="font-semibold text-foreground">{currentProfile.name}</span>{' '}
                  to{' '}
                  <span className="font-semibold text-foreground">
                    {orgDetails?.name ?? associationSlug}
                  </span>
                  .
                </p>
              <div className="flex gap-3">
                <Button
                  variant="outline"
                  className="flex-1"
                  disabled={isAttaching}
                  onClick={() => navigate({ to: '/dashboard', replace: true })}
                >
                  Cancel
                </Button>
                <Button
                  className="flex-1"
                  disabled={isAttaching}
                  onClick={handleAttachExistingOrg}
                >
                  {isAttaching ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Linking...
                    </>
                  ) : (
                    <>
                      <CheckCircle2 className="h-4 w-4 mr-2" />
                      Confirm & Link
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  // --- Not logged in — show landing page with MSME banner + auth ---
  if (!user) {
    return (
      <div className="min-h-screen bg-background">
        <div className="container mx-auto px-4 py-12">
          <div className="max-w-lg mx-auto space-y-6">
            {/* MSME org card */}
            <Card>
              <CardHeader className="text-center pb-2">
                <div className="flex items-center justify-center mb-3">
                  {orgDetails.logo ? (
                    <img
                      src={orgDetails.logo}
                      alt={orgDetails.name}
                      className="h-16 w-16 rounded-lg object-cover border"
                    />
                  ) : (
                    <div className="h-16 w-16 rounded-lg bg-primary/10 flex items-center justify-center">
                      <Building2 className="h-8 w-8 text-primary" />
                    </div>
                  )}
                </div>
                <CardTitle className="text-xl">{orgDetails.name}</CardTitle>
              </CardHeader>
              <CardContent className="text-center space-y-4">
                <p className="text-muted-foreground text-sm">
                  You have been invited to register your organization under{' '}
                  <span className="font-medium text-foreground">{orgDetails.name}</span>.
                </p>

                <Button className="w-full" size="lg" onClick={() => setShowAuthDialog(true)}>
                  Sign in or create account to continue
                </Button>

                <p className="text-xs text-muted-foreground">
                  After signing in, you will be guided to set up your organization profile.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>

        <UnifiedAuthDialog
          isOpen={showAuthDialog}
          onClose={handleAuthSuccess}
          returnTo={`/join/${associationSlug}`}
        />
      </div>
    );
  }

  // Fallback (e.g. user logged in + has profile, redirect is in-flight)
  return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <Loader2 className="h-8 w-8 animate-spin text-primary" />
    </div>
  );
}
