export const JOB_ROLES_BY_INDUSTRY = {
  'Manufacturing': [
    'Machine Operator',
    'Production Worker',
    'Quality Inspector',
    'Assembly Line Worker',
    'Welder',
    'Electrician',
    'Maintenance Technician',
    'Forklift Operator',
    'Packaging Worker',
    'Supervisor'
  ],
  'Construction': [
    'Mason',
    'Carpenter',
    'Electrician',
    'Plumber',
    'Painter',
    'Welder',
    'Heavy Equipment Operator',
    'Construction Worker',
    'Site Supervisor',
    'Safety Officer'
  ],
  'Retail': [
    'Sales Associate',
    'Cashier',
    'Store Manager',
    'Customer Service Representative',
    'Inventory Clerk',
    'Visual Merchandiser',
    'Security Guard',
    'Cleaner',
    'Delivery Person',
    'Stock Boy'
  ],
  'Hospitality': [
    'Waiter/Waitress',
    'Cook',
    'Housekeeping',
    'Front Desk Clerk',
    'Bartender',
    'Kitchen Helper',
    'Bellboy',
    'Laundry Attendant',
    'Security Guard',
    'Maintenance Worker'
  ],
  'Healthcare': [
    'Nursing Assistant',
    'Ward Boy',
    'Cleaner',
    'Security Guard',
    'Ambulance Driver',
    'Medical Equipment Technician',
    'Pharmacy Assistant',
    'Lab Technician',
    'Receptionist',
    'Caregiver'
  ],
  'Transport': [
    'Driver',
    'Delivery Boy',
    'Warehouse Worker',
    'Loading/Unloading Worker',
    'Vehicle Cleaner',
    'Mechanic',
    'Conductor',
    'Traffic Controller',
    'Parking Attendant',
    'Fuel Station Attendant'
  ],
  'Agriculture': [
    'Farm Worker',
    'Tractor Operator',
    'Harvester',
    'Irrigation Worker',
    'Livestock Caretaker',
    'Gardener',
    'Fertilizer Applicator',
    'Crop Inspector',
    'Dairy Worker',
    'Poultry Worker'
  ],
  'Textile': [
    'Tailor',
    'Cutter',
    'Ironer',
    'Seamstress',
    'Pattern Maker',
    'Quality Checker',
    'Embroidery Worker',
    'Knitting Machine Operator',
    'Dyeing Worker',
    'Finishing Worker',
    'Fabric Inspector',
    'Alteration Specialist'
  ]
}; 