/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AdminDashboardImport } from './routes/admin-dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as VerifyEmailImport } from './routes/verify.email'
import { Route as JobApplicantsJobIdImport } from './routes/job-applicants.$jobId'
import { Route as AuthResetPasswordImport } from './routes/auth.reset-password'
import { Route as AuthActionImport } from './routes/auth.$action'
import { Route as VerifyEmailErrorImport } from './routes/verify.email.$error'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailRoute = VerifyEmailImport.update({
  id: '/verify/email',
  path: '/verify/email',
  getParentRoute: () => rootRoute,
} as any)

const JobApplicantsJobIdRoute = JobApplicantsJobIdImport.update({
  id: '/job-applicants/$jobId',
  path: '/job-applicants/$jobId',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthActionRoute = AuthActionImport.update({
  id: '/auth/$action',
  path: '/auth/$action',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailErrorRoute = VerifyEmailErrorImport.update({
  id: '/$error',
  path: '/$error',
  getParentRoute: () => VerifyEmailRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth/$action': {
      id: '/auth/$action'
      path: '/auth/$action'
      fullPath: '/auth/$action'
      preLoaderRoute: typeof AuthActionImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/job-applicants/$jobId': {
      id: '/job-applicants/$jobId'
      path: '/job-applicants/$jobId'
      fullPath: '/job-applicants/$jobId'
      preLoaderRoute: typeof JobApplicantsJobIdImport
      parentRoute: typeof rootRoute
    }
    '/verify/email': {
      id: '/verify/email'
      path: '/verify/email'
      fullPath: '/verify/email'
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/verify/email/$error': {
      id: '/verify/email/$error'
      path: '/$error'
      fullPath: '/verify/email/$error'
      preLoaderRoute: typeof VerifyEmailErrorImport
      parentRoute: typeof VerifyEmailImport
    }
  }
}

// Create and export the route tree

interface VerifyEmailRouteChildren {
  VerifyEmailErrorRoute: typeof VerifyEmailErrorRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailErrorRoute: VerifyEmailErrorRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/auth/$action': typeof AuthActionRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/job-applicants/$jobId': typeof JobApplicantsJobIdRoute
  '/verify/email': typeof VerifyEmailRouteWithChildren
  '/verify/email/$error': typeof VerifyEmailErrorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/auth/$action': typeof AuthActionRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/job-applicants/$jobId': typeof JobApplicantsJobIdRoute
  '/verify/email': typeof VerifyEmailRouteWithChildren
  '/verify/email/$error': typeof VerifyEmailErrorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/auth/$action': typeof AuthActionRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/job-applicants/$jobId': typeof JobApplicantsJobIdRoute
  '/verify/email': typeof VerifyEmailRouteWithChildren
  '/verify/email/$error': typeof VerifyEmailErrorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/dashboard'
    | '/auth/$action'
    | '/auth/reset-password'
    | '/job-applicants/$jobId'
    | '/verify/email'
    | '/verify/email/$error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/dashboard'
    | '/auth/$action'
    | '/auth/reset-password'
    | '/job-applicants/$jobId'
    | '/verify/email'
    | '/verify/email/$error'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/dashboard'
    | '/auth/$action'
    | '/auth/reset-password'
    | '/job-applicants/$jobId'
    | '/verify/email'
    | '/verify/email/$error'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DashboardRoute: typeof DashboardRoute
  AuthActionRoute: typeof AuthActionRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  JobApplicantsJobIdRoute: typeof JobApplicantsJobIdRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DashboardRoute: DashboardRoute,
  AuthActionRoute: AuthActionRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  JobApplicantsJobIdRoute: JobApplicantsJobIdRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin-dashboard",
        "/dashboard",
        "/auth/$action",
        "/auth/reset-password",
        "/job-applicants/$jobId",
        "/verify/email"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin-dashboard": {
      "filePath": "admin-dashboard.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/auth/$action": {
      "filePath": "auth.$action.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth.reset-password.tsx"
    },
    "/job-applicants/$jobId": {
      "filePath": "job-applicants.$jobId.tsx"
    },
    "/verify/email": {
      "filePath": "verify.email.tsx",
      "children": [
        "/verify/email/$error"
      ]
    },
    "/verify/email/$error": {
      "filePath": "verify.email.$error.tsx",
      "parent": "/verify/email"
    }
  }
}
ROUTE_MANIFEST_END */
